/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('hu' | 'en') | ('hu' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'main-menu': MainMenu;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'hu' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (
    | {
        background: 'cream' | 'warm' | 'dark' | 'solidDark';
        padding: 'none' | 'small' | 'normal';
        column?:
          | (
              | {
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  primaryCtaText?: string | null;
                  primaryCtaLink?: string | null;
                  secondaryCtaText?: string | null;
                  secondaryCtaLink?: string | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  items: {
                    icon: 'Quote' | 'Award' | 'TrendingUp' | 'Users';
                    tag: string;
                    title: string;
                    desc: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'quoteSlider';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  cards?:
                    | {
                        icon: string;
                        tag?: string | null;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'services';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  floatingCardTitle?: string | null;
                  floatingCardValue?: string | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  ctaText?: string | null;
                  ctaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'about';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  steps?:
                    | {
                        number: string;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  bottomStripTitle?: string | null;
                  bottomStripDesc?: string | null;
                  bottomStripCtaText?: string | null;
                  bottomStripCtaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'methodology';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  testimonials?:
                    | {
                        quote: string;
                        authorName: string;
                        authorTitle: string;
                        authorImage?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'testimonials';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  contactInfo?:
                    | {
                        icon: string;
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contact';
                }
            )[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'oneColumn';
      }
    | {
        background: 'cream' | 'warm' | 'dark' | 'solidDark';
        padding: 'none' | 'small' | 'normal';
        ratio: '1/2-1/2' | '1/3-2/3' | '2/3-1/3' | '1/4-3/4' | '3/4-1/4';
        leftColumn?:
          | (
              | {
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  primaryCtaText?: string | null;
                  primaryCtaLink?: string | null;
                  secondaryCtaText?: string | null;
                  secondaryCtaLink?: string | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  items: {
                    icon: 'Quote' | 'Award' | 'TrendingUp' | 'Users';
                    tag: string;
                    title: string;
                    desc: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'quoteSlider';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  cards?:
                    | {
                        icon: string;
                        tag?: string | null;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'services';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  floatingCardTitle?: string | null;
                  floatingCardValue?: string | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  ctaText?: string | null;
                  ctaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'about';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  steps?:
                    | {
                        number: string;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  bottomStripTitle?: string | null;
                  bottomStripDesc?: string | null;
                  bottomStripCtaText?: string | null;
                  bottomStripCtaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'methodology';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  testimonials?:
                    | {
                        quote: string;
                        authorName: string;
                        authorTitle: string;
                        authorImage?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'testimonials';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  contactInfo?:
                    | {
                        icon: string;
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contact';
                }
            )[]
          | null;
        rightColumn?:
          | (
              | {
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  primaryCtaText?: string | null;
                  primaryCtaLink?: string | null;
                  secondaryCtaText?: string | null;
                  secondaryCtaLink?: string | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  items: {
                    icon: 'Quote' | 'Award' | 'TrendingUp' | 'Users';
                    tag: string;
                    title: string;
                    desc: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'quoteSlider';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  cards?:
                    | {
                        icon: string;
                        tag?: string | null;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'services';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  floatingCardTitle?: string | null;
                  floatingCardValue?: string | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  ctaText?: string | null;
                  ctaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'about';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  steps?:
                    | {
                        number: string;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  bottomStripTitle?: string | null;
                  bottomStripDesc?: string | null;
                  bottomStripCtaText?: string | null;
                  bottomStripCtaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'methodology';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  testimonials?:
                    | {
                        quote: string;
                        authorName: string;
                        authorTitle: string;
                        authorImage?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'testimonials';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  contactInfo?:
                    | {
                        icon: string;
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contact';
                }
            )[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'twoColumn';
      }
    | {
        background: 'cream' | 'warm' | 'dark' | 'solidDark';
        padding: 'none' | 'small' | 'normal';
        leftColumn?:
          | (
              | {
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  primaryCtaText?: string | null;
                  primaryCtaLink?: string | null;
                  secondaryCtaText?: string | null;
                  secondaryCtaLink?: string | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  items: {
                    icon: 'Quote' | 'Award' | 'TrendingUp' | 'Users';
                    tag: string;
                    title: string;
                    desc: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'quoteSlider';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  cards?:
                    | {
                        icon: string;
                        tag?: string | null;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'services';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  floatingCardTitle?: string | null;
                  floatingCardValue?: string | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  ctaText?: string | null;
                  ctaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'about';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  steps?:
                    | {
                        number: string;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  bottomStripTitle?: string | null;
                  bottomStripDesc?: string | null;
                  bottomStripCtaText?: string | null;
                  bottomStripCtaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'methodology';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  testimonials?:
                    | {
                        quote: string;
                        authorName: string;
                        authorTitle: string;
                        authorImage?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'testimonials';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  contactInfo?:
                    | {
                        icon: string;
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contact';
                }
            )[]
          | null;
        middleColumn?:
          | (
              | {
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  primaryCtaText?: string | null;
                  primaryCtaLink?: string | null;
                  secondaryCtaText?: string | null;
                  secondaryCtaLink?: string | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  items: {
                    icon: 'Quote' | 'Award' | 'TrendingUp' | 'Users';
                    tag: string;
                    title: string;
                    desc: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'quoteSlider';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  cards?:
                    | {
                        icon: string;
                        tag?: string | null;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'services';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  floatingCardTitle?: string | null;
                  floatingCardValue?: string | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  ctaText?: string | null;
                  ctaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'about';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  steps?:
                    | {
                        number: string;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  bottomStripTitle?: string | null;
                  bottomStripDesc?: string | null;
                  bottomStripCtaText?: string | null;
                  bottomStripCtaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'methodology';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  testimonials?:
                    | {
                        quote: string;
                        authorName: string;
                        authorTitle: string;
                        authorImage?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'testimonials';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  contactInfo?:
                    | {
                        icon: string;
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contact';
                }
            )[]
          | null;
        rightColumn?:
          | (
              | {
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  primaryCtaText?: string | null;
                  primaryCtaLink?: string | null;
                  secondaryCtaText?: string | null;
                  secondaryCtaLink?: string | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'hero';
                }
              | {
                  items: {
                    icon: 'Quote' | 'Award' | 'TrendingUp' | 'Users';
                    tag: string;
                    title: string;
                    desc: string;
                    id?: string | null;
                  }[];
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'quoteSlider';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  subtitle?: string | null;
                  cards?:
                    | {
                        icon: string;
                        tag?: string | null;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'services';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  image?: (number | null) | Media;
                  floatingCardTitle?: string | null;
                  floatingCardValue?: string | null;
                  bullets?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  ctaText?: string | null;
                  ctaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'about';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  steps?:
                    | {
                        number: string;
                        title: string;
                        desc: string;
                        id?: string | null;
                      }[]
                    | null;
                  bottomStripTitle?: string | null;
                  bottomStripDesc?: string | null;
                  bottomStripCtaText?: string | null;
                  bottomStripCtaLink?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'methodology';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  testimonials?:
                    | {
                        quote: string;
                        authorName: string;
                        authorTitle: string;
                        authorImage?: (number | null) | Media;
                        id?: string | null;
                      }[]
                    | null;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'testimonials';
                }
              | {
                  variant: 'cream' | 'warm' | 'dark';
                  eyebrow?: string | null;
                  title?: string | null;
                  description?: string | null;
                  contactInfo?:
                    | {
                        icon: string;
                        label: string;
                        value: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'contact';
                }
            )[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'threeColumn';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        oneColumn?:
          | T
          | {
              background?: T;
              padding?: T;
              column?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          primaryCtaText?: T;
                          primaryCtaLink?: T;
                          secondaryCtaText?: T;
                          secondaryCtaLink?: T;
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    quoteSlider?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    services?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          cards?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    about?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          image?: T;
                          floatingCardTitle?: T;
                          floatingCardValue?: T;
                          bullets?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          ctaText?: T;
                          ctaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    methodology?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          steps?:
                            | T
                            | {
                                number?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          bottomStripTitle?: T;
                          bottomStripDesc?: T;
                          bottomStripCtaText?: T;
                          bottomStripCtaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    testimonials?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          testimonials?:
                            | T
                            | {
                                quote?: T;
                                authorName?: T;
                                authorTitle?: T;
                                authorImage?: T;
                                id?: T;
                              };
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    contact?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          contactInfo?:
                            | T
                            | {
                                icon?: T;
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        twoColumn?:
          | T
          | {
              background?: T;
              padding?: T;
              ratio?: T;
              leftColumn?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          primaryCtaText?: T;
                          primaryCtaLink?: T;
                          secondaryCtaText?: T;
                          secondaryCtaLink?: T;
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    quoteSlider?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    services?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          cards?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    about?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          image?: T;
                          floatingCardTitle?: T;
                          floatingCardValue?: T;
                          bullets?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          ctaText?: T;
                          ctaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    methodology?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          steps?:
                            | T
                            | {
                                number?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          bottomStripTitle?: T;
                          bottomStripDesc?: T;
                          bottomStripCtaText?: T;
                          bottomStripCtaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    testimonials?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          testimonials?:
                            | T
                            | {
                                quote?: T;
                                authorName?: T;
                                authorTitle?: T;
                                authorImage?: T;
                                id?: T;
                              };
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    contact?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          contactInfo?:
                            | T
                            | {
                                icon?: T;
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              rightColumn?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          primaryCtaText?: T;
                          primaryCtaLink?: T;
                          secondaryCtaText?: T;
                          secondaryCtaLink?: T;
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    quoteSlider?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    services?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          cards?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    about?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          image?: T;
                          floatingCardTitle?: T;
                          floatingCardValue?: T;
                          bullets?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          ctaText?: T;
                          ctaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    methodology?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          steps?:
                            | T
                            | {
                                number?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          bottomStripTitle?: T;
                          bottomStripDesc?: T;
                          bottomStripCtaText?: T;
                          bottomStripCtaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    testimonials?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          testimonials?:
                            | T
                            | {
                                quote?: T;
                                authorName?: T;
                                authorTitle?: T;
                                authorImage?: T;
                                id?: T;
                              };
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    contact?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          contactInfo?:
                            | T
                            | {
                                icon?: T;
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        threeColumn?:
          | T
          | {
              background?: T;
              padding?: T;
              leftColumn?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          primaryCtaText?: T;
                          primaryCtaLink?: T;
                          secondaryCtaText?: T;
                          secondaryCtaLink?: T;
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    quoteSlider?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    services?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          cards?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    about?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          image?: T;
                          floatingCardTitle?: T;
                          floatingCardValue?: T;
                          bullets?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          ctaText?: T;
                          ctaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    methodology?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          steps?:
                            | T
                            | {
                                number?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          bottomStripTitle?: T;
                          bottomStripDesc?: T;
                          bottomStripCtaText?: T;
                          bottomStripCtaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    testimonials?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          testimonials?:
                            | T
                            | {
                                quote?: T;
                                authorName?: T;
                                authorTitle?: T;
                                authorImage?: T;
                                id?: T;
                              };
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    contact?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          contactInfo?:
                            | T
                            | {
                                icon?: T;
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              middleColumn?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          primaryCtaText?: T;
                          primaryCtaLink?: T;
                          secondaryCtaText?: T;
                          secondaryCtaLink?: T;
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    quoteSlider?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    services?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          cards?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    about?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          image?: T;
                          floatingCardTitle?: T;
                          floatingCardValue?: T;
                          bullets?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          ctaText?: T;
                          ctaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    methodology?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          steps?:
                            | T
                            | {
                                number?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          bottomStripTitle?: T;
                          bottomStripDesc?: T;
                          bottomStripCtaText?: T;
                          bottomStripCtaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    testimonials?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          testimonials?:
                            | T
                            | {
                                quote?: T;
                                authorName?: T;
                                authorTitle?: T;
                                authorImage?: T;
                                id?: T;
                              };
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    contact?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          contactInfo?:
                            | T
                            | {
                                icon?: T;
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              rightColumn?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          primaryCtaText?: T;
                          primaryCtaLink?: T;
                          secondaryCtaText?: T;
                          secondaryCtaLink?: T;
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    quoteSlider?:
                      | T
                      | {
                          items?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    services?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          subtitle?: T;
                          cards?:
                            | T
                            | {
                                icon?: T;
                                tag?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    about?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          image?: T;
                          floatingCardTitle?: T;
                          floatingCardValue?: T;
                          bullets?:
                            | T
                            | {
                                text?: T;
                                id?: T;
                              };
                          ctaText?: T;
                          ctaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    methodology?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          steps?:
                            | T
                            | {
                                number?: T;
                                title?: T;
                                desc?: T;
                                id?: T;
                              };
                          bottomStripTitle?: T;
                          bottomStripDesc?: T;
                          bottomStripCtaText?: T;
                          bottomStripCtaLink?: T;
                          id?: T;
                          blockName?: T;
                        };
                    testimonials?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          testimonials?:
                            | T
                            | {
                                quote?: T;
                                authorName?: T;
                                authorTitle?: T;
                                authorImage?: T;
                                id?: T;
                              };
                          stats?:
                            | T
                            | {
                                value?: T;
                                label?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    contact?:
                      | T
                      | {
                          variant?: T;
                          eyebrow?: T;
                          title?: T;
                          description?: T;
                          contactInfo?:
                            | T
                            | {
                                icon?: T;
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  menuItems?:
    | {
        type?: ('link' | 'mega') | null;
        title: string;
        link?: (number | null) | Page;
        megaItems?:
          | {
              icon?: (number | null) | Media;
              title: string;
              description?: string | null;
              link?: (number | null) | Page;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    label?: string | null;
    link?: (number | null) | Page;
    icon?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | (
        | {
            width?: number | null;
            showLogo?: boolean | null;
            content?: string | null;
            socialLinks?:
              | {
                  platform: 'LinkedIn' | 'Twitter' | 'Instagram' | 'Facebook' | 'YouTube';
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textBlock';
          }
        | {
            width?: number | null;
            title: string;
            links?:
              | {
                  label: string;
                  page?: (number | null) | Page;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkBlock';
          }
        | {
            width?: number | null;
            title: string;
            description?: string | null;
            placeholderText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterBlock';
          }
      )[]
    | null;
  bottomBar?: {
    copyright?: string | null;
    legalLinks?:
      | {
          label: string;
          page?: (number | null) | Page;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  favicon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  menuItems?:
    | T
    | {
        type?: T;
        title?: T;
        link?: T;
        megaItems?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
        icon?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        textBlock?:
          | T
          | {
              width?: T;
              showLogo?: T;
              content?: T;
              socialLinks?:
                | T
                | {
                    platform?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        linkBlock?:
          | T
          | {
              width?: T;
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    page?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletterBlock?:
          | T
          | {
              width?: T;
              title?: T;
              description?: T;
              placeholderText?: T;
              id?: T;
              blockName?: T;
            };
      };
  bottomBar?:
    | T
    | {
        copyright?: T;
        legalLinks?:
          | T
          | {
              label?: T;
              page?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}